apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: check-health
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.58
      command: ["/bin/bash", "-c"]
      args:
        - echo "You can add tests here to ensure that your resources are healthy!"
